// SPDX-License-Identifier: AGPL-3.0-or-later

import { z } from 'zod';

/** Every entity id is a UUID, generated by the database. */
export const idSchema = z.uuid();

export type Id = z.infer<typeof idSchema>;
