// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Connection settings for the database scripts, read from the environment
// only. There are no default credentials: a missing value stops the script
// with a message naming the variable. In development, `pnpm db:migrate` and
// friends fill these in from the development Compose file
// (scripts/dev-env.ts).

import { readFileSync } from 'node:fs';
import { isIPv4 } from 'node:net';

export type Env = Readonly<Record<string, string | undefined>>;

/** Read a required, non-secret setting. */
export function readSetting(env: Env, name: string): string {
  const value = env[name];
  if (value === undefined || value === '') {
    throw new Error(`Set ${name}.`);
  }
  return value;
}

/**
 * Read a secret from NAME, or from the file named by NAME_FILE (a mounted
 * Compose or Kubernetes secret). Setting both is an error, so it is always
 * clear which one is in use.
 */
export function readSecret(env: Env, name: string, readFile = readTextFile): string {
  const value = env[name];
  const file = env[`${name}_FILE`];
  if (value && file) {
    throw new Error(`Set ${name} or ${name}_FILE, not both.`);
  }
  const secret = file ? readFile(file).replace(/\r?\n$/, '') : value;
  if (!secret) {
    throw new Error(`Set ${name} or ${name}_FILE.`);
  }
  return secret;
}

function readTextFile(path: string): string {
  return readFileSync(path, 'utf8');
}

/** The database every PostgreSQL server has, used to create and drop others. */
export const MAINTENANCE_DATABASE = 'postgres';

/** PostgreSQL's own databases, which PixelGrant never prepares, migrates or drops. */
const SYSTEM_DATABASES = new Set([MAINTENANCE_DATABASE, 'template0', 'template1']);

/** Database names are generated by scripts/dev-names.ts or chosen by an operator. */
const DATABASE_NAME = /^[a-z_][a-z0-9_]{0,62}$/;

export function readDatabaseName(env: Env, name: string): string {
  const database = readSetting(env, name);
  if (!DATABASE_NAME.test(database)) {
    throw new Error(
      `${name} must be 1 to 63 characters of lower-case letters, digits and underscores, not starting with a digit.`,
    );
  }
  if (SYSTEM_DATABASES.has(database)) {
    throw new Error(
      `${name} names PostgreSQL's own database ${database}. Use a database of its own.`,
    );
  }
  return database;
}

export interface ServerSettings {
  host: string;
  port: number;
}

export function readServer(env: Env): ServerSettings {
  const host = readSetting(env, 'PIXELGRANT_DB_HOST');
  const portText = readSetting(env, 'PIXELGRANT_DB_PORT');
  const port = Number(portText);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('PIXELGRANT_DB_PORT must be a port number from 1 to 65535.');
  }
  return { host, port };
}

/**
 * Whether a database host is this machine: localhost, an address in
 * 127.0.0.0/8, or ::1. Development-only actions, such as accepting the fixed
 * development passwords or dropping a database, refuse any other host.
 */
export function isLoopbackHost(host: string): boolean {
  if (host === 'localhost' || host === '::1' || host === '[::1]') return true;
  return isIPv4(host) && host.startsWith('127.');
}

/** Whether this is development against a server on this machine. */
export function isLocalDevelopment(env: Env): boolean {
  const host = env['PIXELGRANT_DB_HOST'];
  return env['PIXELGRANT_DEV'] === '1' && host !== undefined && isLoopbackHost(host);
}
